apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: dev
spec:
  type: LoadBalancer     # switch to ClusterIP if you want private
  selector: { app: frontend }
  ports:
    - name: http
      port: 80
      targetPort: 8080
